---
title: "Compare Predicted and Measured FlyCodes (F255744)"
author: "Christian Panse"
date: "2017-10-30"
bibliography:
  - NestLink.bib
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{3. Compare Predicted and Measured FlyCodes (F255744).}
  %\VignetteEncoding{UTF-8}
output:
  BiocStyle::html_document
---

The following content is descibed in more detail in @NestLink
(under review  NMETH-A35040).


# Retention Time (RT) versus Sequence-specific retention calculator (SSRC)

```{r fig.retina=1, fig.height=16}
library(NestLink)


# load(url("http://fgcz-ms.uzh.ch/~cpanse/p1875/F255744.RData"))
# F255744 <- as.data.frame.mascot(F255744) 
# now available through ExperimentHub

library(ExperimentHub)
eh <- ExperimentHub(); 

load(query(eh, c("NestLink", "F255744.RData"))[[1]])

par(mfrow = c(4,1))

NestLink:::.ssrc.mascot(F255744, scores = c(10, 20, 40, 50))
```


# Session info

Here is the output of `sessionInfo()` on the system on which this
document was compiled:

```{r sessionInfo, echo=FALSE}
sessionInfo()
```

# References

