---
title: "F246319 prediction and reality"
author: "Christian Panse"
date: "2017-03-04"

vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{NestLink - F246319}
output:
  html_document:
    theme: united	
    toc: true
---

# load

```{r}
library(specL)
```

```{r}
load(url('http://fgcz-ms.uzh.ch/~cpanse/p1875/F246319.RData'))
```


# RT versus SSRC

```{r fig.retina=3}
idx <- which(unlist(lapply(F246319, function(x){grepl("NB_", x$proteinInformation) && x$mascotScore > 30})))

score <- sapply(F246319[idx], function(x){x$mascotScore})
hyd <- sapply(F246319[idx], function(x){ssrc(x$peptideSequence)})
rt <- sapply(F246319[idx], function(x){x$rtinseconds})
peptide <- sapply(F246319[idx], function(x){as.character(x$peptideSequence)})
smoothScatter(hyd ~ rt)
abline(lm(hyd ~ rt), col='red')
cor(hyd , rt)

```


```{r}
freq <- table(strsplit(paste(peptide, collapse=''), ''))

100 * freq / max(freq)

round(100 * freq / max(freq))
```


# C-Term

```{r}
cTerm <- c('WR','WLTVR','WQEGGR','WQSR','WLR')
cTerm.freq <- sapply(cTerm , function(x){sum(grepl(paste(x, "$",sep=''), peptide))})
round(100 * cTerm.freq / sum(cTerm.freq))

```


# AA

```{r}
cTerm <- c('WR$','WLTVR$','WQEGGR$','WQSR$','WLR$')

regexpattern <- paste(c("^GS", cTerm), collapse = '|')
peptide.f <- gsub(regexpattern, "", peptide)

freq <- table(strsplit(paste(peptide.f, collapse=''), ''))

round(100 * freq / sum(freq))


# in-silico
aa_pool_x8 <- c(rep('A', 18), rep('S', 6), rep('T', 12), rep('N', 0), rep('Q', 0), rep('D', 12), 
              rep('E', 12), rep('V', 12), rep('L', 2), rep('F', 1), rep('Y', 4), rep('W', 1), 
              rep('G', 8), rep('P', 12))
table(aa_pool_x8)

table(sapply(peptide.f , nchar))

```

# peptide mass versus retention time

```{r fig.retina=3}
plot(parentIonMass(peptide) ~ rt, col=rgb(0.1,0.1,0.1,0.1), pch=16)
```

# ssrc predicted hydrophobicity value verus rt

```{r fig.retina=3}
plot(sapply(peptide, ssrc) ~ rt, col=rgb(0.1,0.1,0.1,0.1), pch=16,
     xlab = 'measured rt [in sec]',
     ylab = 'ssrc predicted hydrophobicity value')
```