---
title: "p1875 post"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# input Workunit : 160118 - mascot2RData
```{r}
# load("~/Downloads/444589.RData")
# S <- do.call('rbind', lapply(list(F255737, F255744, F255747, F255749, F255751,
#                                F255760, F255761, F255762), 
#                           as.data.frame.mascot))

load(system.file("extdata/WU160118.RData", package = "NestLink"))

S <- WU160118
idx <- grepl("^GS[ASTNQDEFVLYWGP]{7}(WR|WLTVR|WQEGGR|WLR)$", S$pep_seq)
```


```{r}
library(ggplot2)
library(protViz)
SS<-S[idx & S$pep_score > 25,]
SS$chargeInt <- as.integer(substr(SS$query_charge, 0,1))
table(SS$chargeInt)

ggplot(SS, aes(x=moverz * SS$chargeInt, fill = factor(query_charge), colour = factor(query_charge))) +
    geom_histogram(binwidth= 10, alpha=.3, position="identity")+
    labs(title = "Precursor mass to charge frequency plot ")+
    labs(subtitle = "Plotting frequency of precursor masses for each charge state")+
    labs(x = "Precursor mass [neutral mass]", y = "Frequency [counts]")+
    labs(fill="Charge State", colour = "Charge State")+
    scale_x_continuous(breaks = scales::pretty_breaks(8))+
    theme_light()
```

```{r fig.}
plot(rt <- SS$RTINSECONDS, hy <- sapply(as.character(SS$pep_seq), ssrc), pch=16, col=rgb(0.3, 0.3, 0.3, 0.1))
cor(rt, hy, method = 'spearman')
abline(lm(hy ~ rt))
```